# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-23 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_traintype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='name')),
                ('note', models.TextField(blank=True, max_length=4096, verbose_name='note')),
            ],
            options={
                'ordering': ['id'],
                'verbose_name': 'location',
                'verbose_name_plural': 'locations',
            },
        ),
    ]
