# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-23 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='name')),
                ('visits', models.IntegerField(default=0, verbose_name='visits')),
                ('validDays', models.IntegerField(default=0, verbose_name='valid')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('note', models.TextField(blank=True, max_length=4096, verbose_name='note')),
            ],
            options={
                'ordering': ['id'],
                'verbose_name': 'subscription',
                'verbose_name_plural': 'subscriptions',
            },
        ),
    ]
