# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-24 17:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_subscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('duration', models.IntegerField(default=60)),
                ('note', models.TextField(blank=True, max_length=4096)),
            ],
            options={
                'ordering': ['id'],
                'verbose_name': 'group',
                'verbose_name_plural': 'groups',
            },
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='client',
            name='note',
            field=models.TextField(blank=True, max_length=4096),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='location',
            name='note',
            field=models.TextField(blank=True, max_length=4096),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='note',
            field=models.TextField(blank=True, max_length=4096),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='validDays',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='visits',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='note',
            field=models.TextField(blank=True, max_length=4096),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='phone',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='traintype',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='traintype',
            name='note',
            field=models.TextField(blank=True, max_length=4096),
        ),
        migrations.AddField(
            model_name='group',
            name='trainType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='articles.TrainType'),
        ),
        migrations.AddField(
            model_name='group',
            name='trainer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='articles.Trainer'),
        ),
    ]
