# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-17 08:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0013_auto_20161025_2108'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='traintype',
            options={'ordering': ['id'], 'verbose_name': 'traintype', 'verbose_name_plural': 'traintypes'},
        ),
        migrations.AlterField(
            model_name='group',
            name='trainType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='articles.Traintype'),
        ),
        migrations.AlterField(
            model_name='traintype',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='own_traintypes', to=settings.AUTH_USER_MODEL),
        ),
    ]
