# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-17 10:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0014_auto_20161117_1519'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='trainType',
            new_name='traintype',
        ),
        migrations.AlterField(
            model_name='group',
            name='traintype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='articles.Traintype'),
        ),
    ]
