# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-18 07:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0017_auto_20161118_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='traintype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='articles.Traintype'),
        ),
    ]
