# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-23 05:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schedule', '0002_event_color_event'),
        ('articles', '0020_auto_20161118_1427'),
    ]

    operations = [
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ManyToManyField(to='articles.Client')),
            ],
            options={
                'ordering': ['id'],
                'verbose_name': 'train',
                'verbose_name_plural': 'trains',
            },
        ),
        migrations.CreateModel(
            name='Traintemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ManyToManyField(to='articles.Client')),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='traintemplate', to='schedule.Event')),
            ],
            options={
                'ordering': ['id'],
                'verbose_name': 'traintemplate',
                'verbose_name_plural': 'traintemplates',
            },
        ),
        migrations.AlterField(
            model_name='group',
            name='traintype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='articles.Traintype'),
        ),
        migrations.AddField(
            model_name='traintemplate',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='articles.Group'),
        ),
        migrations.AddField(
            model_name='traintemplate',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='articles.Location'),
        ),
        migrations.AddField(
            model_name='traintemplate',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='own_traintemplates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='traintemplate',
            name='trainer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='articles.Trainer'),
        ),
        migrations.AddField(
            model_name='train',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='articles.Group'),
        ),
        migrations.AddField(
            model_name='train',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='articles.Location'),
        ),
        migrations.AddField(
            model_name='train',
            name='occurrence',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='train', to='schedule.Occurrence'),
        ),
        migrations.AddField(
            model_name='train',
            name='trainer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='articles.Trainer'),
        ),
    ]
