# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-23 10:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0021_auto_20161123_1207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='train',
            name='client',
        ),
        migrations.RemoveField(
            model_name='traintemplate',
            name='client',
        ),
        migrations.AlterField(
            model_name='group',
            name='traintype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='articles.Traintype'),
        ),
    ]
